// <auto-generated />
namespace Kosmos.DownloaderServer.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_ExtractTasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ExtractTasks));
        
        string IMigrationMetadata.Id
        {
            get { return "201611251104356_add_ExtractTasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
